### ISSUE TITLE
APQP devliverables are not in latest Aras Version OOTB

### ISSUE THREAD

**Issue by YoannArasLab** [ArasLabs/sample-project-template-apqp#1]
The APQP Project making a deliverable link to items like DFMEA, Control Plan.
These Items are new itemtypes since this template was made. We need to replace these links.
![image](https://user-images.githubusercontent.com/22646995/28365134-93a4e9ce-6c87-11e7-833f-0288558cb0f7.png)

**Comment by EliJDonahue** [comment]
@ABJohnson395 - Find out from Rob which current ItemTypes make the most sense to replace the old DFMEA and Control Plan ItemTypes in this project template, and then update the package.

**Comment by dutoitep** [comment]
@ABJohnson395 any update on resolving this issue with latest OOTB Aras?

**Comment by ABJohnson395** [comment]
@cgillis-aras and @asebastian-aras could you handle this please?

**Comment by cgillis-aras** [comment]
Resolved with #2 and #3

**Comment by victorarias0610** [comment]
Gentlemen, I read somewhere above the links for APQP project plan may be different.. not sure if these were updated or not but would appreciate if someone can help me see if the is a way to download this project Plan. if so can anyone send me a note to victor.r.arias@lmco.com... Greatly appreciated guys
